### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#10]
There is no special separate function for error handling. It is something we need across the function.

The bottom line requirement is to know that something failed, what the IDs / inputs / error msgs were so that:

1. We know there was an error
2. The error is meaningful
3. The function should try to recover and complete as much work as possible.
4. We can retrieve the source data and re-run the function to replicate the error.

**Comment by eafzali** [comment]
All lambda function logs would be available in CloudWatch. So I guess we just need to track and throw appropriate Error if something happened.

**Comment by rimutaka** [comment]
I presume it's all good and proper in there.
