### ISSUE TITLE
Optimizing original image upload path

### ISSUE THREAD

**Issue by eafzali** [hubsy-io/timelapse#12]
Can we use `[bucketname]/originals/[cameraname]/[filename].jpg` instead of `[bucketname]/[cameraname]/full/[filename].jpg` path template? 
Because AWS lambda function supports prefixes and suffixes for event triggers and this way we will use `/originals` (or anything else you prefer) as prefix and '.jpg' as suffix and our lambda will just triggered when cams upload images. Otherwise with the previous path template we should check the path within the lambda function everytime.

**Comment by rimutaka** [comment]
Hm. Are you saying the function will trigger every time we upload a file,
even a resized one? Can you use a wildcard? */full/* ?

**Comment by eafzali** [comment]
Yes, it will trigger.
No, it doesn't support regex or wildcard.

**Comment by rimutaka** [comment]
OK
So shall we have 2 trees then?
One for full and one for resized?

bucket/full/cam1/file1.jpg
bucket/resized/cam1/....

Do as needed.

**Comment by eafzali** [comment]
We can keep your previous structure as is, we just need to consolidate all full folders in a top level folder, so I propose something like this:

bucket/full/cam1/file1.jpg
bucket/full/cam2/file2.jpg
bucket/cam1/resized/file1.jpg
bucket/cam1/exif/...
bucket/cam1/config.json
bucket/cam2/...

**Comment by rimutaka** [comment]
Agree.

**Comment by rimutaka** [comment]
Ehsan, can you update readme as well?

**Comment by eafzali** [comment]
Sure
