### ISSUE TITLE
I need PutObject permission on your s3 bucket.

### ISSUE THREAD

**Issue by eafzali** [hubsy-io/timelapse#13]
I receive this when trying to put some pictures on your bucket.
`A client error (AccessDenied) occurred when calling the PutObject operation: Access Denied`

**Comment by rimutaka** [comment]
You have s3:* for actions. Checking in 20min.

**Comment by rimutaka** [comment]
Ehsan, can only check tomorrow morning.

**Comment by eafzali** [comment]
Ok will continue on my own account for now.

**Comment by rimutaka** [comment]
You were right. It was messed up. Try now?

**Comment by eafzali** [comment]
Still not working i'm able to list but can't upload.

**Comment by rimutaka** [comment]
Can you give me the full arn of ur account? I will add a bucket policy.

**Comment by eafzali** [comment]
I'm using the access key you provided, but I have also sent you my account ARN on Upwork in case you need.

**Comment by rimutaka** [comment]
I added a policy directly to the bucket. Try now?

**Comment by eafzali** [comment]
Still the same:

```bash
MacBook-Pro:timelapse ehsan$ export AWS_DEFAULT_PROFILE=hubsy
MacBook-Pro:timelapse ehsan$ aws s3 ls hubsy-upwork
                           PRE cam1/
                           PRE cam2/
                           PRE cam3/
2016-08-16 05:08:38        498 config.txt
MacBook-Pro:timelapse ehsan$ aws s3 sync res/s3 s3://hubsy-upwork
upload failed: res/s3/cam2/config.json to s3://hubsy-upwork/cam2/config.json A client error (AccessDenied) occurred when calling the PutObject operation: Access Denied
```
