### ISSUE TITLE
Using webpack ES6/babel?

### ISSUE THREAD

**Issue by eafzali** [hubsy-io/timelapse#14]
I usually write ES6 code using babel and webpack. Do you think that would be a good idea to do it here? and also splitting the code into modules to make it more readable?
I wanted things to be simple but I saw that code quality is important for you and you always do good code reviews.

**Comment by rimutaka** [comment]
Good idea.
Let's do modules and better tooling at the next iteration.

**Comment by rimutaka** [comment]
Ehsan, I can't make sense of the solution any more.
We should have 3 functions: image resizing, video encoding, video uploading.

I only see 2.
Also, index.js seems to be identical and is committed twice in 2 separate locations.
