### ISSUE TITLE
Document deployment

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#16]
The access control and deployment were quite ad-hoc. It may be trial and error every time we try to deploy it. Better try to document the steps and do a few test deployments.

**Comment by eafzali** [comment]
Would you like to prepare a [terraform](www.terraform.io) file for this?

**Comment by rimutaka** [comment]
Never used it. Do you think it will cover everything we need?

**Comment by eafzali** [comment]
Yes, it should cover everything.
