### ISSUE TITLE
Slideshow

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#17]
Suggest a simple slideshow that can be easily embedded into a website so show a number of images from an index. 

Ideally, we just give it a link to an IDX file and it pulls the images from the list.
In practice, we will either need to wrap it into more JS to read the file for it or modify the IDX files to suit the slideshow script.

It should have back/forward feature, list of thumbs or some dots for the number of slides.

Let's agree on the slideshow, implement it on a test page and post instructions in readme.md.

### Considerations

1. Responsive
2. List of thumbs
3. Flexes with the window size changes on the fly (e.g. changed rotation or resized the browser window)
4. Open source
5. Has a pager of sorts, ideally with thumbs
6. Quick to load
7. Lazy image loading
8. Can have HTML overlay with text, e.g. date time or some data from exif. (nice to have)
9. Click to view larger size (nice to have)
10. Doesn't require extensive HTML containers - one line JS embed.
11. Can be placed on S3/CloudFront for easy distribution.

**Comment by rimutaka** [comment]
https://www.lobstervision.tv/home#/camera-0-0 is interesting, but it's a whole page with a calendar, zoom, etc. We need something much simpler that can be embedded into a page with a line of JS.

**Comment by eafzali** [comment]
I couldn't see that, I needed to login

**Comment by rimutaka** [comment]
The slideshow sample doesn't work for me. 
https://s3.amazonaws.com/hubsy-upwork/slidshow.html
What am I doing wrong?

**Comment by eafzali** [comment]
I've create gh page at https://hubsy-io.github.io/timelapse/ You should add CORS for `hubsy-io.github.io` to the bucket to make it work.
http://docs.aws.amazon.com/AmazonS3/latest/UG/EditingBucketPermissions.html

**Comment by rimutaka** [comment]
Ehsan, I create this

<CORSConfiguration>
     <CORSRule>
         <AllowedOrigin>hubsy-io.github.io</AllowedOrigin>
         <AllowedMethod>GET</AllowedMethod>
         <MaxAgeSeconds>3000</MaxAgeSeconds>
         <AllowedHeader>*</AllowedHeader>
     </CORSRule>
</CORSConfiguration>

Quickly read the doco, but got no time to really dig into it.
What S3 resources is it using? The images or something else?
Just tell me what needs to be done exactly.

https://hubsy-io.github.io/timelapse/ gives me a blank page in FF and 
CR. Sorry, got no time to troubleshoot. Over to you.

**Comment by eafzali** [comment]
The images and the index files, here's the error:

> XMLHttpRequest cannot load https://s3.amazonaws.com/hubsy-upwork/cam3/resized/sd/idx/last100.txt. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://hubsy-io.github.io' is therefore not allowed access.

And I guess you have revoked the public read access because I cannot open the resized images and index files any more from the browser it gives 403 error.

**Comment by rimutaka** [comment]
https://s3.amazonaws.com/hubsy-upwork/cam1/resized/sd/idx/last100.txt 
works for me.

**Comment by rimutaka** [comment]
Updated CORS to

<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
     <CORSRule>
         <AllowedOrigin>https://hubsy-io.github.io</AllowedOrigin>
         <AllowedMethod>GET</AllowedMethod>
         <MaxAgeSeconds>3000</MaxAgeSeconds>
         <AllowedHeader>*</AllowedHeader>
     </CORSRule>
</CORSConfiguration>

**Comment by eafzali** [comment]
I think these two options are much better: 
* https://github.com/kenwheeler/slick/
* https://github.com/nolimits4web/Swiper

**Comment by rimutaka** [comment]
Swiper is good. It's killing my FF, though. Need to test it in another browser.
Shall we start committing the code here or open another repo?

**Comment by rimutaka** [comment]
1. Update readme with CORS, sources and other info.
2. Commit somewhere
3. Can we parse the file name and use an HTML overlay for the image date/time? Ideally we need to get it from EXIF, but the file name will do for now.
4. Can the embedding JS be reduced to one line with params?
5. Do you know if we can open up CORS to *? Not sure AWS will take it. Just trying to minimise the set up effort.

**Comment by eafzali** [comment]
1,2) Code is commited to gh-pages branch. I'll add a guide and link to sample file on readme. 
3) Yeah that would be possible will do it
4) Yeah that's possible will do that as well
5) again yes possible with * as allowed origin, you can find configuration here: http://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html
