### ISSUE TITLE
Create a config file

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#2]
Format: JSON

Different parts of the file are specified in different sections of readme.md.
This issue reflects only a snapshot in time of what is in the config file.

* **file name**: config.json
* **file location**: the root of the bucket and the root of the camera folder. The format is identical at both levels, but the camera level overwrites the bucket level. 

Read and store the config in a global var outside of the handler function. It will give us some form of caching. Since the function can be invoked for different cameras the cache needs to be qualified using a key for that scope.

### File merging rules

Top level tags in the lower level file replace the tag in the root. E.i. the entire "resize" tag should be replaced. If the tag is empty then treat it as removal of the top level tag.

**Comment by rimutaka** [comment]
{
	"version": "1",
	"original-folder": "full",
	"exif": {
		"folder": "exif",
		"retain-tags": ["Exif.Image.Orientation", "Exif.Image.DateTime", "Exif.Photo.DateTimeOriginal"]
	},
	"crop": {
		"top": 100,
		"left": 100,
		"width": 300,
		"height": 300
	},
	"resize": [{
		"folder": "resized/fhd",
		"width": 1920,
		"height": 1080,
		"compression": 75
	}, {
		"folder": "resized/hd",
		"width": 1080,
		"height": 720,
		"compression": 75
	}, {
		"folder": "resized/small",
		"width": 500,
		"height": 500,
		"compression": 50
	}]
}

**Comment by rimutaka** [comment]
A sample config file is placed in the root of the bucket. 
Folder cam1 has no config file.
Folders cam2 & cam3 have config files different from the root.

**Comment by eafzali** [comment]
Why `.txt` when it contains JSON?

**Comment by rimutaka** [comment]
Good point. Using .json will not set the right mime type automatically. Can
be either way. It probably should be application/json anyway.

**Comment by rimutaka** [comment]
The camera level config is optional. Use the top level config if none exists.
2016-08-30T02:21:24.361Z 729e8ead-6e58-11e6-874d-837e65e4596f
{
    "errorMessage": "Error: Error while reading configs: AccessDenied: Access Denied\n    at /var/task/index.js:67:11\n    at process._tickDomainCallback (node.js:407:9)"
}

cam1 folder had no config and I was getting the error msg above.

**Comment by eafzali** [comment]
I've already handled NoSuchKey error for this:
https://github.com/hubsy-io/timelapse/blob/master/index.js#L58
and it was working correctly as I tested, but now it's giving `AccessDenied` Error not `NoSuchKey`. I'm wondering how could it be possible!?

**Comment by eafzali** [comment]
Ok I found the reason here:
https://mauricio.github.io/2015/09/19/access-denied-on-s3-for-an-unknown-object.html
we should also allow Listing to our lambda function as well as GetObject.

**Comment by rimutaka** [comment]
Can you treat an error as no such key?
The end result looks the same to me.

**Comment by eafzali** [comment]
You mean I ignore all errors when getting config files? I think that wouldn't be a good idea. It may make disguise us on out later debugging sessions.
I guess just adding the `ListBucket` permission to our lambda function role will resolve this issue.

**Comment by rimutaka** [comment]
It now has bucket-wide "s3:GetObject", "s3:ListBucket". I will upload a few files during the day and see how it goes.
