### ISSUE TITLE
Resizing errors

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#23]
Some resized images get corrupted. Happened more than once. The original images looked OK.
This is just a note. Probably lack of resources. Need to follow up later.

Example: https://s3.amazonaws.com/hubsy-upwork/cam1/resized/fhd/20160914T160432.032Z.jpg

**Comment by eafzali** [comment]
Can't open it. Access denied!

**Comment by rimutaka** [comment]
Its a generic error. I get the file is corrupt when i go via cli or console.

**Comment by rimutaka** [comment]
@eafzali , we do have a problem, sir. Look at hubsy-timelapse-1/cam1/resized/fhd. There is a lot of files with 0-length. Their full versions are OK. Can you dig into it?

**Comment by eafzali** [comment]
Seems that it was just resource problem. I've upgraded Lambda RAM to 1024 and it's working properly!

**Comment by rimutaka** [comment]
Did you document it in readme?

**Comment by rimutaka** [comment]
What about the deployment script? 
Also, change the defaults region to US-East on all resources.
