### ISSUE TITLE
Embed timestamp

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#24]
1. Embed a timestamp into the image.
2. Embed  date/time into the video.

Let's make it configurable where the timestamp is placed and what size it is. The style will be fixed.

It's not clear if using images with a date/time is more efficient than embedding it directly via FFmpeg.
The problem is, we may want the timestamp to be in video only and not in the images.

**Comment by Velro** [comment]
It looks like I could do this through FFmpeg.  We would just have to add a parameter to the FFmpeg wrapper for the starting timecode, so the time of the earliest frame in the batch. Then parameters described by @rimutaka. I think this would be faster than adding a timecode to each image before creating the video.

**Comment by rimutaka** [comment]
Images don't always come at equal intervals. You need to supply 
date/time for every image separately.

**Comment by Velro** [comment]
Okay I think we'd want to do it per-image then, using a tool like ImageMagick, it's like the FFmpeg for images. FFmpeg's timestamp support is too limited, looks like you just pass it a starting time and it extrapolates the timestamps based on a constant framerate. 

Ehsan would have to have me do the file renaming like I had it at one point, or pass me an array of times as a parameter. Or this could be a separate module, which might be good if you think that you might want other per-image manipulation work in the future.

**Comment by rimutaka** [comment]
OK. We already do image resizing and cropping with IM. Will insert a timestamp as well. @eafzali, this is up your alley then.
