### ISSUE TITLE
Image resizing performance

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#25]
It takes whooping 24 seconds per 7MB image to be resized into 3 other images and indexes updated.

Profile the execution, identify the bottle necks and fine tune the resources. 
This includes video production as well.

There are 2 considerations:
1 - the cost (must be optimal)
2 - time to show (must be minimal)

I'd say that 5s should be the longest it runs.

Post test cases with results here and copy into readme.
## Test cases

Data in: 16MP, 12MP, 8MP, 5MP, FHD, HD images
Operations: resize, crop, rotate, add 30 frames to a video
Stages of interest: initialise the function (hot, cold), download from S3, image manipulation, saving to S3.
Other permutations: check if saving with different compression level affects the performance much (I doubt it will, other than faster copying of much smaller files).

Source data: it will be in hubsy-2 bucket (to be supplied later today).

**Comment by rimutaka** [comment]
Would this one be faster? 
https://github.com/libjpeg-turbo/libjpeg-turbo

**Comment by eafzali** [comment]
Using this config:
```js
{
    version: '1',
    'exif-retain': ['DateTime', 'DateTimeOriginal'],
    resize: [{
        folder: 'resized/sd',
        width: 640,
        height: 720,
        quality: 50
    }, {
        folder: 'resized/hd',
        width: 1280,
        height: 720,
        quality: 70
    }, {
        folder: 'resized/fhd',
        width: 1920,
        height: 1080,
        quality: 80
    }],
    video: {
        width: 1920,
        height: 1080,
        source: 'resized/fhd',
        fps: 2,
        frameLimit: 30
    }
}
```
 | 16MP | 8MP | FHD
----- | ----- | ----- | ----
Orient | ~1 sec | ~1 sec | <<1 sec
Resize | 7 - 10 sec | 2 - 3 sec | ~1 sec
Total | 10 - 14 sec | 4.2 - 5.5 sec | ~3 sec

Overal load/remove time: 1-2 sec
