### ISSUE TITLE
Video gen release review

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#34]
1) IAM policies are out of sync
- I maintained hubsy-upload with `"arn:aws:s3:::[BUCKET]/full/*", "arn:aws:s3:::[BUCKET]/log/*"`
  which has **/log/** in it.
- looks like there are policy duplicates for different zones/buckets.

2) The default config should be

```
{
  "version": "1",
  "exif-retain": ["DateTime", "DateTimeOriginal"],
  "resize": [
    {
      "folder": "resized/sd",
      "width": 640,
      "height": 720,
      "compression": 50
    },
    {
      "folder": "resized/hd",
      "width": 1280,
      "height": 720,
      "compression": 30
    },
    {
      "folder": "resized/fhd",
      "width": 1920,
      "height": 1080,
      "compression": 20
    }
  ],
  "video": {
    "width": 1920,
    "height": 1080,
    "source": "resized/fhd",
    "fps": 2
  }
}
```

**Comment by eafzali** [comment]
We should update policy using https://github.com/hubsy-io/timelapse/blob/master/infrastructure/policy.tf only and use `apex infra apply` to apply it.
