### ISSUE TITLE
Image resizing

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#4]
Resize images and store them in S3 as per the config file using a λ-function attached to the bucket as a handler for `s3:ObjectCreated:*`.

```
"resize": [
    {"folder": "resized/fhd", "width": 1920, "height": 1080, "compression": 50}
    {"folder": "resized/hd", "width": 1080, "height": 720, "compression": 50}
    {"folder": "resized/small", "width": 500, "height": 500, "compression": 50}
  ],
```

1. Take the original image from `full` folder.
2. Read `resize` section of the config file.
3. Create and save the resized images into their respective folders. Note, it's S3. Whenever we talk about folders they are just prefixes in object names.
4. The file names of the resized files must be the same for the resized files as for the originals.
5. Set the right mime type and http caching = forever.
6. Make sure there is no original exif data in the resized image. It should be removed altogether. Usually it is what happens by default if all you do is just copy streams, but sometimes processors copy it over. There is a separate issue for copying some of the exif metadata.

**Comment by eafzali** [comment]
Should we ignore or respect aspect ratio? 
Maybe we can make it configurable: `"ignoreAspectRatio": true` and respect it by default.

**Comment by eafzali** [comment]
It's now doing as I proposed.

**Comment by rimutaka** [comment]
Ah, I looked at the code and I see what you mean now. The resize dimensions are the maximum bounding box. We need to retain the ratio. So both sides are resized proportionally and no size is breaking the bounding box.

**Comment by eafzali** [comment]
So it's doing the same exact thing now. You can also set `ignoreAspectRatio` to `true` to force it resize image to the exact width/height and ignore aspect ratio. Thats an extra option.

**Comment by rimutaka** [comment]
Looks like the MIME type is not set on resized images. It should be image/jpeg.

**Comment by rimutaka** [comment]
Ehsan, still getting wrong mimes on some images. https://s3.amazonaws.com/hubsy-upwork/cam1/resized/fhd/20160902T133916.016Z.jpg

**Comment by eafzali** [comment]
Have you recently uploaded this? I've not changed the mime type of previous uploaded images.

**Comment by rimutaka** [comment]
Yes, its a new upload.

**Comment by eafzali** [comment]
Oh sorry, would you please try it again. I think I didn't deployed the latest version on AWs.

**Comment by rimutaka** [comment]
All good.
