### ISSUE TITLE
Extract EXIF data

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#6]
Extract exif data from the original image and store it in a text file in `exif` folder retaining the same file name, but the replace `.jpg` with `.txt`.

Change the mime type to text/text and set the caching to forever.

Not sure what format ImageMagick returns for exif, but I presume it is some some of text. I suggest we just dump it as is. I'm not sure what use case there is for exif, so no point doing too much here.

**Comment by rimutaka** [comment]
All good, but the MIME type is not set. Check all other files for setting the mime type. It was in the requirements.

**Comment by eafzali** [comment]
Yeah, sorry about the ContentTypes I added them on all uploads.
