### ISSUE TITLE
Index images

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#8]
The resizing function should maintain the following indexes for every size:

* last.txt
* last100.txt
* today.txt
* 24hr.txt
* 7days.txt
* 30days.txt

These files should be created in folder `[resized]/idx` as plain text files with immediate expiration. Actually, not sure about the immediate expiration. We need to set it so that the request is sent every time, but the browser can take `304 Not Modified` response from S3/CloudFront.

The format of the file should be a simple list of absolute URLs, one per line. Hopefully it will be easy to feed it into various slideshows.

The function should cache the results for every index file to reuse it for another size. They will be identical apart from the path to the size folder.

As a new file is added, the old files need to be removed. If no files are being added then no files are removed. There will be a separate issue for a function that removes files from the index regardless of the new additions.

**Comment by eafzali** [comment]
Why indexing in text file? You want to avoid using DynamoDB?

**Comment by rimutaka** [comment]
DynamoDB seems to be an overkill at this stage. The txt files can be read
by JS in some slideshow. They are small and pretty basic.

**Comment by eafzali** [comment]
Why overkill? in case of costs you mean? I'm not sure about the upload rate of your images but it may cause some race conditions and that would be challenging to handle. And also these file's data will become staled after a day if no new image uploads.

**Comment by rimutaka** [comment]
There will be few minutes interval between them. But good point.
It is possible for images to be uploaded in batches. That will screw things
up.

I'll try to think of a workaround. Lets not use a db at this stage.

**Comment by eafzali** [comment]
According to which timezone should it calculate `today.txt` and `24hr.txt` indexes? I guess the default timezone of lambda functions is GMT. That's OK? is it even important?

**Comment by rimutaka** [comment]
I was thinking it should be in the timezone of the camera. Just use
whatever values are supplied in exif.

Its very unlikely a cam will be moved between time zones.

**Comment by eafzali** [comment]
There's not EXIF data about time zone. All times will be stored as UTC timestamps in EXIF. the only workaround I could find is to send the GPS coordinates of the image to some web services and retrieve it's time zone based on that, so that would be a little challenging. Are you willing to do that now or we can use UTC timezone for now? or maybe we can add a field to the config file?
