### ISSUE TITLE
Copy EXIF data to resized

### ISSUE THREAD

**Issue by rimutaka** [hubsy-io/timelapse#9]
The resizing function should remove all original exif data, which probably happens by default anyway.

Then we need to add some of it back to the resized files as per the config file:

 `"exif-retain": ["Exif.Image.Orientation", "Exif.Image.DateTime", "Exif.Photo.DateTimeOriginal"]`

This is a list of tag names to be copied, if present.

**Comment by rimutaka** [comment]
I see this in the logs
```
2016-09-05T00:06:35.878Z 99d692d1-72fc-11e6-bdec-ad11f54422eb Clearing EXIF data retaining [ 'Exif.Image.Orientation',
'Exif.Image.DateTime',
'Exif.Photo.DateTimeOriginal' ]
```
but I don't see the actual data in the resized images.

There is some exif data in the image. Flickr doesn't pick it up.
E.g. https://www.flickr.com/photos/67148940@N00/29173478550/in/dateposted-public/ from 
Folder: 	fhd
Name: 	20160905T121510.010Z.jpg

*http://regex.info/exif.cgi* gave me no useful metadata either, but it said the exif part took up 17.4kb. Strange.

I do see the full meadata in flickr and the regex viewer with the original image.

What am I doing wrong?

**Comment by eafzali** [comment]
You should change the config to:
```js
[ 
  'Orientation',
  'DateTime',
  'DateTimeOriginal' 
]
```
instead of 
```js
[ 
  'Exif.Image.Orientation',
  'Exif.Image.DateTime',
  'Exif.Photo.DateTimeOriginal' 
]
```

**Comment by rimutaka** [comment]
Why?
